#!/usr/bin/env bash
# ==============================================================================
# HARPER MODULE 06: FINALIZE
# ==============================================================================
# ARCHITECTURAL OVERVIEW:
# This module concludes the processing session by applying final legal disclaimers
# to master catalogs, generating aggregated JSON indices (search and catalog),
# and reporting the final session duration metrics.
#
# FUTURE MAINTENANCE NOTES:
# - Ensure that any new metadata index paths remain synced with standard project
#   directories (e.g., `../engine-room-records/json/`).
# - Relies on `jq` to parse and aggregate line-delimited JSON (`.jsonl`) generated
#   by previous modules into standard JSON arrays.
# ==============================================================================

echo "   📝 HARPER: Applying AI Production Disclaimers to Master Catalogs..."
# Traverse and apply standard disclaimer blocks to discography markdown files
find "$SEARCH_PATH" -name "*-discography-and-lyrics.md" | while read -r master_file; do
    # Only inject the disclaimer if it hasn't been appended already
    if ! grep -q "### Production Disclaimer" "$master_file"; then
        echo "---" >> "$master_file"
        echo "### Production Disclaimer" >> "$master_file"
        echo "All lyrics and lore are human-authored. Audio composition, instrumentation, and vocals were generated via AI platforms." >> "$master_file"
        echo "" >> "$master_file"
    fi
done

# Cleanup temporary sorting lists and backup files generated by sed
rm -f "$TEMP_SORTED_ALBUMS"
find "$SEARCH_PATH" -name "*-discography-and-lyrics.md" -exec sed -i.bak '//d' {} + 2>/dev/null
find "$SEARCH_PATH" -name "*.bak" -type f -delete 2>/dev/null

echo "🎧 HARPER: Finalizing the Search Index..."
# Aggregate track-level metadata generated across albums into a unified search index
if [ -s "$TEMP_SEARCH_INDEX" ]; then
    jq -s '.' "$TEMP_SEARCH_INDEX" > "$METADATA_FILE"
    rm "$TEMP_SEARCH_INDEX"
    echo "   ✅ HARPER: Index saved to $METADATA_FILE"
else
    echo "   ⚠️  HARPER: Search index was empty. Skipping metadata generation."
    rm -f "$TEMP_SEARCH_INDEX"
fi

# Ensure the destination directory exists for the final catalog
CATALOG_DIR="../engine-room-records/json"
mkdir -p "$CATALOG_DIR"
CATALOG_FILE="$CATALOG_DIR/master-catalog.json"

echo "🎧 HARPER: Compiling the Master ISRC/ERR Catalog..."
# Compile ISRC and internal IDs into a centralized master catalog
if [ -s "$TEMP_CATALOG_INDEX" ]; then
    jq -s '.' "$TEMP_CATALOG_INDEX" > "$CATALOG_FILE"
    rm "$TEMP_CATALOG_INDEX"
    echo "   ✅ HARPER: Catalog saved to $CATALOG_FILE"
else
    echo "   ⚠️  HARPER: Catalog index was empty. Skipping generation."
    rm -f "$TEMP_CATALOG_INDEX"
fi

# --- TIME CALCULATION ---
# Calculate the total wall-clock time spent processing
END_EPOCH=$(date +%s)
END_TIME_STR=$(date +"%Y-%m-%d %I:%M:%S %p")
DURATION_SEC=$((END_EPOCH - START_EPOCH))

DURATION_HOURS=$((DURATION_SEC / 3600))
DURATION_MIN=$(((DURATION_SEC % 3600) / 60))
DURATION_REM_SEC=$((DURATION_SEC % 60))

# --- FINAL SESSION REPORTING ---
# Print tailored completion messages based on execution mode
if [ "$METADATA_ONLY" = true ]; then
    echo "🎧 HARPER: Session complete! Metadata repacked and ready for the distro network."
else
    echo "🎧 HARPER: Session complete! The radio edits are public, and the master tapes are locked in the vault."
fi

echo "   ⏰ Session Ended: $END_TIME_STR"
# Format output nicely depending on whether duration exceeded an hour
if [ "$DURATION_HOURS" -gt 0 ]; then
    echo "   ⏱️  Total Processing Time: "$DURATION_HOURS"h "$DURATION_MIN"m "$DURATION_REM_SEC"s"
else
    echo "   ⏱️  Total Processing Time: "$DURATION_MIN"m "$DURATION_REM_SEC"s"
fi