server {
    server_name raggiesoft.com www.raggiesoft.com;
    root /var/www/raggiesoft.com;

    access_log /var/log/nginx/raggiesoft_access.log;
    error_log /var/log/nginx/raggiesoft_error.log;

    index amanda/elara.php;

    location ~ /\. {
        deny all;
    }

    location ^~ /includes/components/apps/ {
        try_files $uri $uri/ =404;
        location ~ \.php$ {
            include snippets/fastcgi-php.conf;
            fastcgi_pass unix:/var/run/php/php8.5-fpm.sock;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
        }
    }

    location ^~ /includes/ {
        deny all;
        return 404;
         }

    location ~* \.(gif|png|jpe?g|svg|webp|ico)$ {
        valid_referers none blocked server_names
                       *.engineroom-records.com engineroom-records.com
                       ~\.google\. ~\.bing\. ~\.yahoo\. ~\.duckduckgo\. ~\.yandex\.
                       ~\.ask\. ~\.lycos\. ~\.altavista\.;
        if ($invalid_referer) {
            return 302 https://assets.raggiesoft.com/common/images/no-hotlink.jpg;
        }
        expires 30d;
        add_header Cache-Control "public, no-transform";
        try_files $uri $uri/ =404;
    }

    location / {
        try_files $uri $uri/ /amanda/elara.php?$query_string;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php/php8.5-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    error_page 403 /amanda/errors/403.php;
    error_page 404 /amanda/errors/404.php;
    error_page 500 /amanda/errors/500.php;
    error_page 502 /amanda/errors/502.php;
    error_page 503 /amanda/errors/503.php;
    error_page 504 /amanda/errors/504.php;

    location ^~ /amanda/errors/ {
        internal;
    }

    listen 443 ssl;
    ssl_certificate /etc/nginx/ssl/raggiesoft.pem;
    ssl_certificate_key /etc/nginx/ssl/raggiesoft.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
}

server {
    if ($host = www.raggiesoft.com) {
        return 301 https://$host$request_uri;
    }
    if ($host = raggiesoft.com) {
        return 301 https://$host$request_uri;
    }
    listen 80;
        server_name raggiesoft.com www.raggiesoft.com;
    return 404;
}
