server {
    server_name books.raggiesoft.com;
    root /var/www/raggiesoft-book-library;

    access_log /var/log/nginx/books.raggiesoft_access.log;
    error_log /var/log/nginx/books.raggiesoft_error.log;

    # Security through obscurity protocol:
    # Public directory: eleanor
    # PHP Router file: isabel.php
    index eleanor/isabel.php;

    location ~ /\. {
        deny all;
    }

    # Route everything through the hidden router
    location / {
        try_files $uri $uri/ /eleanor/isabel.php?$query_string;
    }

    # Pass PHP scripts to FastCGI
    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php/php8.5-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    # Catch the Cloudflare HTTPS proxy traffic
    listen 443 ssl;
    listen [::]:443 ssl;
    
    # The wildcard SSL certificates
    ssl_certificate /etc/nginx/ssl/raggiesoft.pem;
    ssl_certificate_key /etc/nginx/ssl/raggiesoft.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
}

server {
    listen 80;
    listen [::]:80;
    server_name books.raggiesoft.com;

    if ($host = books.raggiesoft.com) {
        return 301 https://$host$request_uri;
    }
    return 404;
}
