server {
    listen 80;
    listen [::]:80;

    # Catch the Cloudflare HTTPS proxy traffic
    listen 443 ssl;
    listen [::]:443 ssl;

    # The wildcard SSL certificates
    ssl_certificate /etc/nginx/ssl/raggiesoft.pem;
    ssl_certificate_key /etc/nginx/ssl/raggiesoft.key;

    # The root of the domain, keeping Celeste hidden inside
    root /var/www/nebulae.raggiesoft.com;

    server_name nebulae.raggiesoft.com;

    # Route everything through the hidden router
    location / {
        try_files $uri /celeste/lyra.php?$query_string;
    }

    # Pass PHP scripts to FastCGI
    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php/php8.5-fpm.sock;
            }

    # Block access to hidden files/directories
    location ~ /\. {
        deny all;
    }
}

